### PR TITLE
Adding more details to startup instructions

### PR DESCRIPTION
**Pull request by evelinag**
Addresses issue #96

### CODE REVIEW

**Comment by tjdodwell** [comment]
Following your instructions I get the following error when I navigate to http://0.0.0.0:5001/

`The current API prefix ('/api/v2') was not found in your request. Please check that you are running the expected version of BlueBird.`

---

In following new instructions, for me at least it looks like two requirements for blueSky are not included in install. Note needs

`pip install pyopengl pyopengl-accelerate`


--- 

A minor comment

`cd ../bluebird` is correct as you will be in a new terminal, rather than in a parallel folder `/bluesky`

**Comment by thobson88** [comment]
> Following your instructions I get the following error when I navigate to http://0.0.0.0:5001/
> 
> The current API prefix ('/api/v2') was not found in your request. Please check that you are running the expected version of BlueBird.

This is the (rather unhelpful) error when an API request is malformed. A valid request looks like, e.g., `http://0.0.0.0:5001/api/v2/siminfo`. I've updated the README to clarify this.

**Comment by evelinag** [comment]
Regarding the missing requirements - they shouldn't be necessary for the Bluesky headless install?

**Comment by thobson88** [comment]
That's right. If Bluesky is installed with the `--headless` flag then the pyopengl packages aren't required.

**Pull request merged**
